version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.0.0
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm test
            - run:
                name: Deploy Master to Heroku
                command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master